Forum/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.Data;
using Microsoft.EntityFrameworkCore;

namespace Forum.Controllers
{
    public class HomeController : Controller
    {
        private readonly ForumDbContext context;

        public HomeController(ForumDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            List<Topic> topics = context.Topics
                .Include(t => t.Autor)
                .Include(t => t.Comments)
                .ThenInclude(c => c.Author)
                .OrderByDescending(t => t.CreateDate)
                .ThenByDescending(t => t.LastUpdatedDate)
                .ToList();

            return View(topics);
        }
    }
}

Forum/Controllers/TopicController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Forum.Data;
using Forum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System;

namespace Forum.Controllers
{
    public class TopicController : Controller
    {
        private readonly ForumDbContext context;

        public TopicController(ForumDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Topic topic = context.Topics
                .Include(t => t.Autor)
                .Include(c => c.Comments)
                .ThenInclude(a => a.Author)
                .Where(t => t.Id == id)
                .SingleOrDefault();

            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }
            
            return View(topic);
        }

        /// <summary>
        /// Creating
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        //Add Postmethod Create Topic
        [HttpPost]
        [Authorize]
        public IActionResult Create(Topic topic)
        {
            if (ModelState.IsValid)
            {
                topic.CreateDate = DateTime.Now;
                topic.LastUpdatedDate = DateTime.Now;

                string autorId = context.Users
                    .Where(u => u.UserName == User.Identity.Name)
                    .First().Id;

                topic.AutorId = autorId;
                context.Topics.Add(topic);
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        /// <summary>
        /// Deleding
        /// </summary>
        /// <param name="id">Topic ID</param>
        /// <returns></returns>
        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var topic = context.Topics.Include(t => t.Autor).SingleOrDefault(m => m.Id == id);

            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        //Add Postmethod Delete Topic
        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            Topic topic = context.Topics.Include(t => t.Autor).SingleOrDefault(m => m.Id == id);
            if (!(topic == null))
            {
                context.Topics.Remove(topic);
                context.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Editing
        /// </summary>
        /// <param name="id">Topic ID</param>
        /// <returns></returns>
        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var topic = context.Topics.Include(t => t.Autor).SingleOrDefault(m => m.Id == id);

            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Topic currToppic)
        {
            Topic topic = context.Topics.Include(t => t.Autor).SingleOrDefault(m => m.Id == currToppic.Id);
            if (!(topic == null))
            {
                return RedirectToAction("Index", "Home");
            }
            topic.Description = currToppic.Description;
            topic.Title = topic.Title;
            topic.LastUpdatedDate = DateTime.Now;
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Forum/Views/Home/Index.cshtml
@model IEnumerable<Topic>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <div class="row forum-container">
        <section class="col-md-9 col-sm-12 article-wrapper">
            <p>
                <a asp-controller="Topic" asp-action="Create" class="btn btn-default">Create New Topic</a>
            </p>

            @foreach (var topic in Model)
            {
                <article class="forum-post">
                    <div class="head-post">
                        <h2 class="post-title">
                            <a asp-controller="Topic" asp-action="Details" asp-route-id="@topic.Id">@topic.Title</a>
                        </h2>
                        <p>
                            <span class="user-wrap">
                                <span class="cell">
                                    <span class="user-name">Author: @topic.Autor.UserName</span>
                                </span>
                            </span>
                            <span class="user-wrap">
                                <span class="cell">
                                    <span class="user-name">Created Date: @topic.CreateDate.ToString("HH:mm dd/MMM/yyyy")</span>
                                </span>
                            </span>
                        </p>
                    </div>
                    <div class="meta-info">
                        <div class="col-md-6 last-replay">
                            <div class="table-holder">
                                <div class="last-replay-inner cell">
                                    <span class="cell">Last activity: </span>
                                    <span class="cell replay-date">@topic.LastUpdatedDate.ToString("HH:mm dd/MMM/yyyy")</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            }
        </section>
    </div>
</div>